#!/bin/bash -l
set -x

export PS4='$SECONDS + '
date

source $ROOT_GODAS_DIR/modulefiles/module-setup.sh.inc
module purge
module use -a $ROOT_GODAS_DIR/modulefiles
cd $ROOT_GODAS_DIR/modulefiles
module load godas.fcst
module list

#############################
# Source relevant config files
#############################
configs="base fcst"
export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export jobid=${job}.${PBS_JOBID:-$$}
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY

##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-"godas"}
export RUN=${RUN:-"data"}
export inistep='restart'
export confignamevarfornems=$nems_temp

###############################################################
# Run relevant exglobal script

${FORECASTSH:-$ROOT_GODAS_DIR/scripts/exglobal_fcst_nemsfv3gfs.sh.ecf}
status=$?
[[ $status -ne 0 ]] && exit $status
##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

date
exit 0
