#!/bin/bash -l
set -e

source $ROOT_GODAS_DIR/modulefiles/module-setup.sh.inc
module purge
module use -a $ROOT_GODAS_DIR/modulefiles
cd $ROOT_GODAS_DIR/modulefiles
module load godas.fcst
module list

cat <<EOF
#================================================================================
#================================================================================
# JJOB_PREP_FORECAST
#   Set up DIRs, make input files, copy over fix files 
#================================================================================
#================================================================================
EOF

#############################
# Source relevant config files
#############################
configs="base fcst"
export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done

CDATE=${CDATE:-${PDY}${cyc}}
CDUMP=${CDUMP:-"godas"}

COMIN=${ROTDIR}/${CDUMP}.${PDY}/${cyc}
if [ ! -d $COMIN ]; then mkdir -p $COMIN; fi

cp /scratch1/NCEPDEV/nems/emc.nemspara/RT/DATM-MOM6-CICE5/master-20191106/MEDIATOR_2011100100/mediator_* $COMIN

echo "running preparation step"
